package com.debdut.anchordi.runtime

/**
 * Creates an instance of T, optionally using the container to resolve dependencies.
 *
 * Implementations are generated by KSP. For [Inject] constructors, the factory
 * will request dependencies from the container and pass them to the constructor.
 */
interface Factory<out T : Any> {
    fun create(container: AnchorContainer): T
}
